/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactFormInput = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([ContactFormInput], [ContactSubmission], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactFormInput = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([ContactFormInput], [ContactSubmission], []),
  });
};

export const init = ({ IDL }) => { return []; };